/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * One endpoint evaluates one arithmetic operation on one or two operands.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number is
 * parsed by a browser into an IEEE-754 double, which would silently destroy the
 * exactness the server just computed: `0.1 + 0.2` would arrive as
 * `0.30000000000000004` after a round trip through `JSON.parse`. Strings cross the
 * wire intact and are converted to a decimal type on each side.
 *
 * Results carry full precision. Rounding for display is the frontend's business and
 * never re-enters a calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import type {
  CalculationRequest,
  CalculationResult,
  ErrorEnvelope
} from './model';


export type calculateResponse200 = {
  data: CalculationResult
  status: 200
}

export type calculateResponse400 = {
  data: ErrorEnvelope
  status: 400
}

export type calculateResponse422 = {
  data: ErrorEnvelope
  status: 422
}

export type calculateResponseSuccess = (calculateResponse200) & {
  headers: Headers;
};
export type calculateResponseError = (calculateResponse400 | calculateResponse422) & {
  headers: Headers;
};

export type calculateResponse = (calculateResponseSuccess | calculateResponseError)

export const getCalculateUrl = () => {




  return `/api/calculate`
}

/**
 * The request is a discriminated union on `operation`. The discriminator selects
 * the operand arity: `sqrt` takes one operand, every other operation takes two.
 * @summary Evaluate one arithmetic operation.
 */
export const calculate = async (calculationRequest: CalculationRequest, options?: RequestInit): Promise<calculateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getCalculateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(calculationRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: calculateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as calculateResponse
}



