/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import type {
  CalculationRequest,
  CalculationResponse,
  ErrorDocument
} from './model';


export type createCalculationResponse200 = {
  data: CalculationResponse
  status: 200
}

export type createCalculationResponse400 = {
  data: ErrorDocument
  status: 400
}

export type createCalculationResponse415 = {
  data: ErrorDocument
  status: 415
}

export type createCalculationResponse422 = {
  data: ErrorDocument
  status: 422
}

export type createCalculationResponseSuccess = (createCalculationResponse200) & {
  headers: Headers;
};
export type createCalculationResponseError = (createCalculationResponse400 | createCalculationResponse415 | createCalculationResponse422) & {
  headers: Headers;
};

export type createCalculationResponse = (createCalculationResponseSuccess | createCalculationResponseError)

export const getCreateCalculationUrl = () => {




  return `/api/calculations`
}

/**
 * The request carries a calculation resource with no `id`, which JSON:API
 * permits for a resource originating at the client. The response carries the
 * same resource with a server-assigned `id` and the computed `result`.
 *
 * The response is `200 OK`, not `201 Created`, and deliberately so: nothing
 * is stored, so there is no location to point a `Location` header at and no
 * `self` link that would resolve. The `id` identifies this evaluation, not a
 * retrievable record.
 * @summary Evaluate one arithmetic operation.
 */
export const createCalculation = async (calculationRequest: CalculationRequest, options?: RequestInit): Promise<createCalculationResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getCreateCalculationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/vnd.api+json', ...getHeaders(options?.headers) },
    body: JSON.stringify(calculationRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createCalculationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCalculationResponse
}



