/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * One endpoint evaluates one arithmetic operation on one or two operands.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number is
 * parsed by a browser into an IEEE-754 double, which would silently destroy the
 * exactness the server just computed: `0.1 + 0.2` would arrive as
 * `0.30000000000000004` after a round trip through `JSON.parse`. Strings cross the
 * wire intact and are converted to a decimal type on each side.
 *
 * Results carry full precision. Rounding for display is the frontend's business and
 * never re-enters a calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * The request is a discriminated union on `operation`. The discriminator selects
 * the operand arity: `sqrt` takes one operand, every other operation takes two.
 * @summary Evaluate one arithmetic operation.
 */
export const calculateBodyOneOperandsItemMax = 52;


export const calculateBodyOneOperandsItemRegExp = new RegExp('^-?[0-9]{1,25}(\\.[0-9]{1,25})?$');
export const calculateBodyOneOperandsMin = 2;
export const calculateBodyOneOperandsMax = 2;

export const calculateBodyTwoOperandsItemMax = 52;


export const calculateBodyTwoOperandsItemRegExp = new RegExp('^-?[0-9]{1,25}(\\.[0-9]{1,25})?$');
export const calculateBodyTwoOperandsMax = 1;



export const CalculateBody = zod.union([zod.object({
  "operation": zod.enum(['add', 'subtract', 'multiply', 'divide', 'percent', 'power']),
  "operands": zod.array(zod.string().max(calculateBodyOneOperandsItemMax).regex(calculateBodyOneOperandsItemRegExp).describe('A decimal number in plain notation, at most 25 integer and 25 fractional\ndigits. Scientific notation is not accepted. The bound is stated once here and\nenforced by both generated layers. Rationale in ADR-0004.\n')).min(calculateBodyOneOperandsMin).max(calculateBodyOneOperandsMax)
}).describe('An operation on two operands.'),zod.object({
  "operation": zod.enum(['sqrt']),
  "operands": zod.array(zod.string().max(calculateBodyTwoOperandsItemMax).regex(calculateBodyTwoOperandsItemRegExp).describe('A decimal number in plain notation, at most 25 integer and 25 fractional\ndigits. Scientific notation is not accepted. The bound is stated once here and\nenforced by both generated layers. Rationale in ADR-0004.\n')).min(1).max(calculateBodyTwoOperandsMax)
}).describe('An operation on one operand.')]).describe('Discriminated on `operation`. Six values map to the two-operand shape and\n`sqrt` to the one-operand shape, so operand arity is a property of the contract\nrather than a check written twice. Rationale in ADR-0003.\n')

export const calculateResponseResultRegExp = new RegExp('^-?[0-9]+(\\.[0-9]+)?([eE][-+]?[0-9]+)?$');


export const CalculateResponse = zod.object({
  "result": zod.string().regex(calculateResponseResultRegExp)
}).describe('The exact result, at the full precision of the server\'s decimal context, which\nis Python\'s default of twenty-eight significant digits. The client rounds for\ndisplay and must chain subsequent operations on this value, never on what the\nscreen shows.\n')
