/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * One endpoint evaluates one arithmetic operation on one or two operands.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number is
 * parsed by a browser into an IEEE-754 double, which would silently destroy the
 * exactness the server just computed: `0.1 + 0.2` would arrive as
 * `0.30000000000000004` after a round trip through `JSON.parse`. Strings cross the
 * wire intact and are converted to a decimal type on each side.
 *
 * Results carry full precision. Rounding for display is the frontend's business and
 * never re-enters a calculation.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * `percent` is `a / 100 * b`, that is "a percent of b": `percent(20, 50)` is
 * `10`. The postfix percent of physical calculators is not implemented, because
 * its meaning depends on the pending operation, which would put an arithmetic
 * rule in the interface.
 *
 * `power` takes the base then the exponent. No exponent bound is declared: the
 * decimal context's own range rejects a catastrophic exponent in microseconds,
 * so a contract-level bound would be machinery that protects nothing.
 */
export type BinaryOperation = typeof BinaryOperation[keyof typeof BinaryOperation];


export const BinaryOperation = {
  add: 'add',
  subtract: 'subtract',
  multiply: 'multiply',
  divide: 'divide',
  power: 'power',
  percent: 'percent',
} as const;
