/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * A decimal number: up to 25 integer digits, 30 fractional digits and an
 * optional exponent.
 *
 * **Operands and results share this one grammar, deliberately.** A
 * calculator chains, so every result must be submittable as the next
 * operand. An operand type narrower than the result type would make a
 * service that cannot accept its own output: dividing one by three returns
 * 28 significant digits, and multiplying that by three would be rejected.
 *
 * The bounds are stated once here and enforced by both generated layers.
 * Rationale in ADR-0004.
 * @maxLength 64
 * @pattern ^-?[0-9]{1,25}(\.[0-9]{1,30})?([eE][-+]?[0-9]{1,6})?$
 */
export type Decimal = string;
