/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * One endpoint evaluates one arithmetic operation on one or two operands.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number is
 * parsed by a browser into an IEEE-754 double, which would silently destroy the
 * exactness the server just computed: `0.1 + 0.2` would arrive as
 * `0.30000000000000004` after a round trip through `JSON.parse`. Strings cross the
 * wire intact and are converted to a decimal type on each side.
 *
 * Results carry full precision. Rounding for display is the frontend's business and
 * never re-enters a calculation.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * The stable, machine-readable reason. Clients branch on this and never on
 * `message`, whose wording belongs to the server and may change.
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export const ErrorCode = {
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNKNOWN_OPERATION: 'UNKNOWN_OPERATION',
  WRONG_OPERAND_COUNT: 'WRONG_OPERAND_COUNT',
  INVALID_OPERAND: 'INVALID_OPERAND',
  OPERAND_OUT_OF_RANGE: 'OPERAND_OUT_OF_RANGE',
  DIVISION_BY_ZERO: 'DIVISION_BY_ZERO',
  NEGATIVE_SQRT: 'NEGATIVE_SQRT',
  UNDEFINED_RESULT: 'UNDEFINED_RESULT',
  RESULT_OVERFLOW: 'RESULT_OVERFLOW',
} as const;
