/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorObject } from './errorObject';

/**
 * JSON:API requires errors to be an array at the top level, and forbids
 * `data` and `errors` from coexisting. One shape for every failure at every
 * status means the client has one error path rather than one per failure
 * mode. See ADR-0005.
 */
export interface ErrorDocument {
  /** @minItems 1 */
  errors: ErrorObject[];
}
