/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorCode } from './errorCode';
import type { ErrorSource } from './errorSource';

export interface ErrorObject {
  /** The HTTP status code, as a string, per JSON:API. */
  status: string;
  code: ErrorCode;
  /** A short summary, the same for every occurrence of a code. */
  title: string;
  /**
     * What went wrong this time. Owned by the server and rendered by the
     * client as it arrives: the client holds no table of its own, so a new
     * code displays correctly with no frontend change.
     */
  detail?: string;
  source?: ErrorSource;
}
