/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * The stable, machine-readable reason, carried in JSON:API's `code` member.
 * Clients branch on this, never on `title` or `detail`.
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export const ErrorCode = {
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNKNOWN_OPERATION: 'UNKNOWN_OPERATION',
  WRONG_OPERAND_COUNT: 'WRONG_OPERAND_COUNT',
  INVALID_OPERAND: 'INVALID_OPERAND',
  OPERAND_OUT_OF_RANGE: 'OPERAND_OUT_OF_RANGE',
  DIVISION_BY_ZERO: 'DIVISION_BY_ZERO',
  NEGATIVE_SQRT: 'NEGATIVE_SQRT',
  UNDEFINED_RESULT: 'UNDEFINED_RESULT',
  RESULT_OVERFLOW: 'RESULT_OVERFLOW',
} as const;
