/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * One endpoint evaluates one arithmetic operation on one or two operands.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number is
 * parsed by a browser into an IEEE-754 double, which would silently destroy the
 * exactness the server just computed: `0.1 + 0.2` would arrive as
 * `0.30000000000000004` after a round trip through `JSON.parse`. Strings cross the
 * wire intact and are converted to a decimal type on each side.
 *
 * Results carry full precision. Rounding for display is the frontend's business and
 * never re-enters a calculation.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Structured context for the failure. Shape depends on the code.
 */
export type ErrorDetails = { [key: string]: unknown };
