/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ResultAttributes } from './resultAttributes';

/**
 * A calculation as the server returns it, with its result.
 */
export interface EvaluatedCalculationResource {
  type: 'calculations';
  /**
     * Assigned by the server to identify this evaluation. It is not a
     * retrievable record: nothing is stored, so no `self` link is offered
     * and no `GET` will find it.
     */
  id: string;
  attributes: ResultAttributes;
}
