/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * A decimal number in plain notation, at most 25 integer and 25 fractional
 * digits. Scientific notation is not accepted. Rationale in ADR-0004.
 * @maxLength 52
 * @pattern ^-?[0-9]{1,25}(\.[0-9]{1,25})?$
 */
export type Operand = string;
