/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Posting a calculation resource evaluates one arithmetic operation and returns
 * the same resource with its `result` filled in.
 *
 * Operands and results are JSON **strings**, never JSON numbers. A JSON number
 * is reparsed by a browser into an IEEE-754 double, which would destroy the
 * exactness the server just computed: `0.1 + 0.2` would come back as
 * `0.30000000000000004` after `JSON.parse`. Results carry full precision, and
 * rounding for display is the client's business and never re-enters a
 * calculation.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { Decimal } from './decimal';
import type { ResultAttributesOperation } from './resultAttributesOperation';

/**
 * The request's own attributes, echoed back, plus the result. Echoing them
 * keeps the response self-describing, which matters because nothing is
 * stored and the client cannot fetch the calculation again to see what was
 * asked.
 */
export interface ResultAttributes {
  operation: ResultAttributesOperation;
  /**
     * @minItems 1
     * @maxItems 2
     */
  operands: Decimal[];
  /**
     * The exact result, at the full precision of the server's decimal
     * context (28 significant digits), in its canonical form: trailing
     * zeros left by the arithmetic are stripped, which changes the
     * representation and not the value. A result too large to write
     * plainly keeps an exponent.
     *
     * Clients round for display only and must chain subsequent operations
     * on this value, never on what the screen shows. See ADR-0004.
     */
  result: Decimal;
}
