# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-01T12:19:56+00:00

from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum
from uuid import UUID


class Decimal(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A decimal number: up to 25 integer digits, 30 fractional digits and an\noptional exponent.\n\n**Operands and results share this one grammar, deliberately.** A\ncalculator chains, so every result must be submittable as the next\noperand. An operand type narrower than the result type would make a\nservice that cannot accept its own output: dividing one by three returns\n28 significant digits, and multiplying that by three would be rejected.\n\nThe bounds are stated once here and enforced by both generated layers.\nRationale in ADR-0004.\n",
            examples=["0.1", "-42", "0.3333333333333333333333333333", "9.999E+74"],
            max_length=64,
            pattern="^-?[0-9]{1,25}(\\.[0-9]{1,30})?([eE][-+]?[0-9]{1,6})?$",
            title="Decimal",
        ),
    ]


class BinaryOperation(Enum):
    add = "add"
    subtract = "subtract"
    multiply = "multiply"
    divide = "divide"
    power = "power"
    percent = "percent"


class BinaryAttributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: Literal["add", "subtract", "multiply", "divide", "percent", "power"]
    operands: Annotated[list[Decimal], Field(max_length=2, min_length=2)]


class UnaryAttributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: Literal["sqrt"]
    operands: Annotated[list[Decimal], Field(max_length=1, min_length=1)]


class CalculationAttributes(RootModel[BinaryAttributes | UnaryAttributes]):
    root: Annotated[
        BinaryAttributes | UnaryAttributes,
        Field(
            description="Discriminated on `operation`, so operand arity is a property of the\ncontract rather than a check written twice. Rationale in ADR-0003.\n",
            discriminator="operation",
            title="CalculationAttributes",
        ),
    ]


class CalculationResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["calculations"]
    attributes: CalculationAttributes


class Operation(Enum):
    add = "add"
    subtract = "subtract"
    multiply = "multiply"
    divide = "divide"
    power = "power"
    percent = "percent"
    sqrt = "sqrt"


class ResultAttributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: Operation
    operands: Annotated[list[Decimal], Field(max_length=2, min_length=1)]
    result: Annotated[
        Decimal,
        Field(
            description="The exact result, at the full precision of the server's decimal\ncontext (28 significant digits), in its canonical form: trailing\nzeros left by the arithmetic are stripped, which changes the\nrepresentation and not the value. A result too large to write\nplainly keeps an exponent.\n\nClients round for display only and must chain subsequent operations\non this value, never on what the screen shows. See ADR-0004.\n",
            examples=["0.3", "1.414213562373095048801688724"],
        ),
    ]


class EvaluatedCalculationResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["calculations"]
    id: Annotated[
        UUID,
        Field(
            description="Assigned by the server to identify this evaluation. It is not a\nretrievable record: nothing is stored, so no `self` link is offered\nand no `GET` will find it.\n"
        ),
    ]
    attributes: ResultAttributes


class ErrorCode(Enum):
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNKNOWN_OPERATION = "UNKNOWN_OPERATION"
    WRONG_OPERAND_COUNT = "WRONG_OPERAND_COUNT"
    INVALID_OPERAND = "INVALID_OPERAND"
    OPERAND_OUT_OF_RANGE = "OPERAND_OUT_OF_RANGE"
    DIVISION_BY_ZERO = "DIVISION_BY_ZERO"
    NEGATIVE_SQRT = "NEGATIVE_SQRT"
    UNDEFINED_RESULT = "UNDEFINED_RESULT"
    RESULT_OVERFLOW = "RESULT_OVERFLOW"


class ErrorSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pointer: Annotated[str | None, Field(examples=["/data/attributes/operands/1"])] = None
    parameter: str | None = None


class ErrorObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Annotated[
        str, Field(description="The HTTP status code, as a string, per JSON:API.", examples=["422"])
    ]
    code: ErrorCode
    title: Annotated[
        str, Field(description="A short summary, the same for every occurrence of a code.")
    ]
    detail: Annotated[
        str | None,
        Field(
            description="What went wrong this time. Owned by the server and rendered by the\nclient as it arrives: the client holds no table of its own, so a new\ncode displays correctly with no frontend change.\n"
        ),
    ] = None
    source: ErrorSource | None = None


class ErrorDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Annotated[list[ErrorObject], Field(min_length=1)]


class CalculationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: CalculationResource


class CalculationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: EvaluatedCalculationResource
