# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-01T10:13:39+00:00

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, RootModel, constr
from enum import Enum
from typing import Any, Literal


class Operand(RootModel[constr(pattern=r"^-?[0-9]{1,25}(\.[0-9]{1,25})?$", max_length=52)]):
    root: constr(pattern=r"^-?[0-9]{1,25}(\.[0-9]{1,25})?$", max_length=52) = Field(
        ...,
        description="A decimal number in plain notation, at most 25 integer and 25 fractional\ndigits. Scientific notation is not accepted. The bound is stated once here and\nenforced by both generated layers. Rationale in ADR-0004.\n",
        examples=["0.1", "-42", "3.14159265358979323846"],
        title="Operand",
    )


class BinaryOperation(Enum):
    add = "add"
    subtract = "subtract"
    multiply = "multiply"
    divide = "divide"
    power = "power"
    percent = "percent"


class BinaryCalculation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: Literal["add", "subtract", "multiply", "divide", "percent", "power"]
    operands: list[Operand] = Field(..., max_length=2, min_length=2)


class UnaryCalculation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: Literal["sqrt"]
    operands: list[Operand] = Field(..., max_length=1, min_length=1)


class CalculationRequest(RootModel[BinaryCalculation | UnaryCalculation]):
    root: BinaryCalculation | UnaryCalculation = Field(
        ...,
        description="Discriminated on `operation`. Six values map to the two-operand shape and\n`sqrt` to the one-operand shape, so operand arity is a property of the contract\nrather than a check written twice. Rationale in ADR-0003.\n",
        discriminator="operation",
        title="CalculationRequest",
    )


class CalculationResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    result: constr(pattern=r"^-?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$") = Field(
        ..., examples=["0.3", "1.414213562373095048801688724"]
    )


class ErrorCode(Enum):
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNKNOWN_OPERATION = "UNKNOWN_OPERATION"
    WRONG_OPERAND_COUNT = "WRONG_OPERAND_COUNT"
    INVALID_OPERAND = "INVALID_OPERAND"
    OPERAND_OUT_OF_RANGE = "OPERAND_OUT_OF_RANGE"
    DIVISION_BY_ZERO = "DIVISION_BY_ZERO"
    NEGATIVE_SQRT = "NEGATIVE_SQRT"
    UNDEFINED_RESULT = "UNDEFINED_RESULT"
    RESULT_OVERFLOW = "RESULT_OVERFLOW"


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: ErrorCode
    message: str = Field(
        ...,
        description="Human-readable text, owned by the server and rendered by the client as it\narrives. The client holds no table of its own, so a new code displays\ncorrectly with no frontend change.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description="Structured context for the failure. Shape depends on the code."
    )


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: Error
